version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  groups:
    eslint:
      patterns:
        - "@eslint/*"
        - "@typescript-eslint/*"
        - "eslint-*"
        - "eslint"
        - "typescript-eslint"
    tailwind:
      patterns:
        - "@tailwindcss/*"
        - "tailwindcss"
