name: Node.js CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Install dependencies
      run: yarn install
    - name: Build
      run: yarn dist
    - name: Test
      run: yarn test
